services:
  jupyterlab-sparc:
    image: simcore/services/dynamic/jupyterlab-sparc:1.0.4
    ports:
      - "8888:8888"
    environment:
      - DY_SIDECAR_PATH_INPUTS=/tmp/inputs
      - DY_SIDECAR_PATH_OUTPUTS=/tmp/outputs
      - DY_BOOT_OPTION_BOOT_MODE=0
      - DY_SIDECAR_PATH/home/jovyan/work/workspace
    volumes:
      - ${PWD}/validation/workspace:/home/jovyan/work/workspace
      - ${PWD}/validation/inputs:/tmp/inputs
      - ${PWD}/validation/outputs:/tmp/outputs